# This workflow sets the package version for user agent
# when pull request to main branch is opened
# it takes pull request name
# and automatically commit it as a package version
# pull request name should always be a version of a new release

name: cd

on:
  pull_request:
    branches: [ main ]
env:
  PACKAGE_VERSION: ${{ github.event.pull_request.title }}
jobs:
  set-user-agent:
    runs-on: macos-latest-xlarge
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set User Agent
        shell: bash
        run: ./.github/scripts/set-user-agent.sh
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Set User Agent

      - name: Lint CocoaPods
        run: |
          pod lib lint --verbose --no-clean --quick --allow-warnings --platforms=ios WalletConnectSwiftV2.podspec